apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dply
  labels:
    app: nginx-srv
spec:
  selector:
    matchLabels:
      app: nginx-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-srv
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 5m
            memory: "128Mi"
          requests:
            cpu: 5m
            memory: "128Mi"
            
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-srvc
  labels:
    app: nginx-srv
spec:
  selector: 
    app: nginx-srv
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 31217