apiVersion: v1
kind: Service
metadata:
  name: nginx-port
  namespace: kube-exercises
spec:
  type: NodePort
  ports:
  - nodePort: 31717
    port: 80
    targetPort: 80
  selector:
    app: "nginx"
  