apiVersion: v1
kind: Service
metadata:
  name: nginx-ext
  namespace: kube-exercises
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  selector:
    app: nginx
  