apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      version: "1.0"
      app: "nginx"
  template:
    metadata:
      labels:
        name: nginx
        version: "1.0"
        app: "nginx"
    spec:
      containers: 
        - name: nginx
          image: nginx:1.19.4
          ports:
            - name: http
              containerPort: 80