apiVersion: v1
kind: Service
metadata: 
  name: nginx-x5
  labels: 
    name: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name: nginx
    version: "1.0"
  type: LoadBalancer