apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
    version: "1.0"
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: nginx
      app: "nginx"
  template:
    metadata:
      labels:
        name: nginx
        app: "nginx"
        version: "1.0"
    spec:
      containers: 
        - name: nginx
          image: nginx:1.19.4
          ports:
            - name: http
              containerPort: 80